Added check for qty 0 in the order lines and fix the printRecItem method
Wvven/l10n-italy pull request #16
Opened 2024-12-20 16:28 UTC by Wvven

2025-01-07 08:55 UTC, eLBati requested changes

2025-01-07 08:55 UTC, eLBati commented on fiscal_epos_print/static/src/js/Screens/PaymentScreen/PaymentScreen.js
> +        if (receipt.orderlines.some((line) => line.quantity <= 0)) {
Come mai `<=` ? Il problema era relativo a `=`.
Le quantità `< 0` sono usate nel caso dei resi se non sbaglio

2025-01-08 09:55 UTC, Wvven commented on fiscal_epos_print/static/src/js/Screens/PaymentScreen/PaymentScreen.js
> +        if (receipt.orderlines.some((line) => line.quantity <= 0)) {
Verificato, si rientra nel caso del rimborso/annullamento, correggo

2025-01-09 10:00 UTC, eLBati requested changes

2025-01-09 10:00 UTC, eLBati commented on fiscal_epos_print/static/src/js/Screens/PaymentScreen/PaymentScreen.js
> +                body: _t("Order contains products with quantity less than or equal to 0."),
Bisogna modificare anche il messaggio di conseguenza

2025-06-15 12:26 UTC, closed without merging