[IMP] fiscal_epos_print: Adapted closing methods and ePOS widget for Owl / Odoo 17
Wvven/l10n-italy pull request #3
Opened 2024-10-02 13:06 UTC by LorenzoC0

2024-10-02 15:24 UTC, eLBati requested changes

2024-10-02 15:24 UTC, eLBati commented on fiscal_epos_print/static/src/js/epson_epos_print.js
> +        xml += '<printXZReport operator="' + fiscal_op + '" timeout="" />';
`printZReport`

2024-10-02 15:24 UTC, eLBati commented on fiscal_epos_print/static/src/js/epson_epos_print.js
> +    printOpenCashDrawer() {
Visto che non sappiamo se funziona, lo facciamo sparire

2024-10-02 15:24 UTC, eLBati commented on fiscal_epos_print/static/src/js/epson_epos_print.js
> +    printFiscalReprintLast (f_op) {
Se non sappiamo se funziona, lo facciamo sparire

2024-10-02 15:24 UTC, eLBati commented on fiscal_epos_print/static/src/js/epson_epos_print.js
> +    resetPrinter() {
Anche questo

2024-10-03 08:38 UTC, LorenzoC0 commented
@eLBati 
Eliminato il richiesto, testata la chiusura, è ok.

2024-10-07 14:28 UTC, eLBati approved these changes
Grazie

2024-10-07 14:28 UTC, merged